# Generated by Django 5.0.4 on 2024-06-24 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=150, unique=True)),
                ('email', models.CharField(default='', max_length=254, unique=True)),
                ('password1', models.CharField(default='', max_length=128)),
                ('password2', models.CharField(default='', max_length=128)),
            ],
        ),
    ]
