# Generated by Django 5.0.4 on 2024-06-24 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Int',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(default='', max_length=150, unique=True)),
                ('bhTN1', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bhTN2', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bhSO', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='OrAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=150, unique=True)),
                ('email', models.CharField(default='', max_length=254, unique=True)),
                ('password1', models.CharField(default='', max_length=128)),
                ('password2', models.CharField(default='', max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='SoMME',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(default='', max_length=150, unique=True)),
                ('attach2g3g', models.DecimalField(decimal_places=2, max_digits=10)),
                ('attach4g', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pdpact2g3g', models.DecimalField(decimal_places=2, max_digits=10)),
                ('attach3g', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sau2g3g', models.BigIntegerField()),
                ('sau4g', models.BigIntegerField()),
                ('pdp', models.BigIntegerField()),
                ('bearer', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Tn1MME',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(default='', max_length=150, unique=True)),
                ('attach2g3g', models.DecimalField(decimal_places=2, max_digits=10)),
                ('attach4g', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pdpact2g3g', models.DecimalField(decimal_places=2, max_digits=10)),
                ('attach3g', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sau2g3g', models.BigIntegerField()),
                ('sau4g', models.BigIntegerField()),
                ('pdp', models.BigIntegerField()),
                ('bearer', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Tn2MME',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(default='', max_length=150, unique=True)),
                ('attach2g3g', models.DecimalField(decimal_places=2, max_digits=10)),
                ('attach4g', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pdpact2g3g', models.DecimalField(decimal_places=2, max_digits=10)),
                ('attach3g', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sau2g3g', models.BigIntegerField()),
                ('sau4g', models.BigIntegerField()),
                ('pdp', models.BigIntegerField()),
                ('bearer', models.BigIntegerField()),
            ],
        ),
    ]
