# Generated by Django 5.0.4 on 2024-05-29 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DashApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
