# Generated by Django 5.0.4 on 2024-07-18 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DashApp', '0002_soepg_somme_tn1epg_tn1mme_tn2mme_tn2vepg'),
    ]

    operations = [
        migrations.CreateModel(
            name='Int',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(default='', max_length=150, unique=True)),
                ('bhTN1', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bhTN2', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bhSO', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bhGlobal', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
    ]
